"""Add project_id to DataSource

Revision ID: f85869d115de
Revises: f15cb096d61a
Create Date: 2025-09-04 12:24:17.170081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85869d115de'
down_revision: Union[str, Sequence[str], None] = 'f15cb096d61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasources', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'datasources', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasources', type_='foreignkey')
    op.drop_column('datasources', 'project_id')
    # ### end Alembic commands ###
