services:
  api:
    build: ./psha-api
    container_name: psha-api
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./psha-api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development   # default → bisa override saat deploy
    depends_on:
      - db

  web:
    build: ./psha-web
    container_name: psha-web
    volumes:
      - ./psha-web:/usr/src/app
    ports:
      - "5173:5173"
    env_file:
      - .env.development
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: psha-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psha -d pshadb"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env.development
    depends_on:
      - db

volumes:
  db_data:
