[project]
name = "sha-web"

# =========================
# Backend FastAPI + OpenQuake
# =========================
[services.backend]
name = "sha-api"
path = "psha-api"
type = "docker"

[services.backend.env]
DATABASE_URL = "postgresql+psycopg2://psha_prod:supersecret@psha-db:5432/pshadb_prod"
APP_HOST = "0.0.0.0"
APP_PORT = "8000"

# =========================
# Frontend React (Vite)
# =========================
[services.frontend]
name = "sha-web"
path = "psha-web"
type = "docker"
build_command = "docker build -t psha-web ."
start_command = "docker run -p 8080:8080 psha-web"


[services.frontend.env]
VITE_API_URL = "https://sha-api-production.up.railway.app/api/v1"
VITE_SAVE_MODE = "server"
VITE_APP_NAME = "PSHA Web"

# =========================
# PostgreSQL Service
# =========================
[services.db]
name = "sha-db"
type = "postgresql"
env = { 
  POSTGRES_USER = "psha_prod",
  POSTGRES_PASSWORD = "supersecret",
  POSTGRES_DB = "pshadb_prod"
}
