[project]
name = "psha-web"

# =========================
# Backend FastAPI + OpenQuake
# =========================
[services.backend]
name = "psha-api"
path = "psha-api"
type = "docker"

[services.backend.env]
DATABASE_URL = "postgresql+psycopg2://psha_prod:supersecret@psha-db:5432/pshadb_prod"
APP_HOST = "0.0.0.0"
APP_PORT = "8000"

# =========================
# Frontend React (Vite)
# =========================
[services.frontend]
name = "psha-web"
path = "psha-web"
type = "static"
build_command = "npm install && npm run build"
start_command = "npx serve -s dist"

[services.frontend.env]
VITE_API_URL = "http://psha-api:8000"  # internal service name Railway

# =========================
# PostgreSQL Service
# =========================
[services.db]
name = "psha-db"
type = "postgresql"
env = { 
  POSTGRES_USER = "psha_prod",
  POSTGRES_PASSWORD = "supersecret",
  POSTGRES_DB = "pshadb_prod"
}
