[project]
name = "psha-web"

# =========================
# Backend FastAPI
# =========================
[services.backend]
name = "psha-api"
path = "psha-api"
type = "docker"

[services.backend.env]
DATABASE_URL = "postgresql+psycopg2://psha_prod:supersecret@psha-db:5432/pshadb_prod"
APP_HOST = "0.0.0.0"
APP_PORT = "8000"

# =========================
# Frontend React Vite
# =========================
[services.frontend]
name = "psha-web"
path = "psha-web"       # HARUS folder yang ada package.json
type = "docker"         # pakai docker, bukan static
build_command = "docker build -t frontend ."
start_command = "docker run -p $PORT:$PORT frontend"

[services.frontend.env]
VITE_API_URL = "https://sha-api-production.up.railway.app/api/v1"

# =========================
# PostgreSQL Service
# =========================
[services.db]
name = "psha-db"
type = "postgresql"
env = { 
  POSTGRES_USER = "psha_prod",
  POSTGRES_PASSWORD = "supersecret",
  POSTGRES_DB = "pshadb_prod"
}
