# Gunakan Python resmi
FROM python:3.11-slim

# Atur working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy semua kode backend
COPY . .

# Expose port FastAPI
EXPOSE 8000

# Jalankan server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
